import { expect, test, type Page } from '@playwright/test'
import { compactValue } from '../src/lib/format'
import type { Dashboard, MetricKey } from '../src/types'

async function ask(page: Page, text: string) {
  const input = page.getByRole('textbox', { name: '向销售分析助手提问' })
  await input.fill(text)
  await page.getByRole('button', { name: '发送问题', exact: true }).click()
  await expect(input).toBeEnabled({ timeout: 30_000 })
  await expect(page.locator('.chat-message.user').last()).toContainText(text)
}
async function login(page: Page, account = 'admin') {
  await page.goto('/')
  await page.getByRole('textbox', { name: '账号', exact: true }).fill(account)
  await page.getByLabel('密码', { exact: true }).fill('demo123')
  await page.getByRole('button', { name: '进入工作台', exact: true }).click()
  await expect(page.getByRole('heading', { name: '销售分析工作台' })).toBeVisible()
  await expect(page.locator('.metric-skeleton')).toHaveCount(0)
}

test('real backend: login, dashboard, query, charts, CSV, follow-up, refresh, reset, scope isolation and mobile', async ({ page, context }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  let protectedResultId = ''
  await test.step('admin login and five KPI cards match authorized backend totals', async () => {
    await login(page)
    await expect(page.locator('.mode-badge')).toContainText('MOCK')
    const response = await context.request.get('/api/dashboard?start=2025-01-01&end=2026-01-01')
    expect(response.ok()).toBeTruthy()
    const dashboard = await response.json() as Dashboard
    await expect(page.locator('.metric-card')).toHaveCount(5)
    for (const [index, metric] of ['sales_amount', 'order_count', 'units_sold', 'avg_order_value', 'gross_profit'].entries()) {
      await expect(page.locator('.metric-card').nth(index).locator('.metric-value')).toHaveText(compactValue(dashboard.totals![metric as MetricKey], metric))
    }
    await expect(page.locator('.analysis-column canvas').first()).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('01-admin-dashboard.png'), fullPage: true })
  })
  await test.step('date filter and invalid period do not leave stale current metrics', async () => {
    await page.getByRole('button', { name: '2024年', exact: true }).click()
    await expect(page.locator('.section-caption')).toContainText('2024-01-01 至 2024-12-31')
    await page.getByRole('button', { name: '2025年', exact: true }).click()
    await expect(page.locator('.section-caption')).toContainText('2025-01-01 至 2025-12-31')
    await page.getByLabel('开始日期', { exact: true }).fill('2025-12-31')
    await page.getByLabel('结束日期', { exact: true }).fill('2025-01-01')
    await page.getByRole('button', { name: '应用', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('开始日期不能晚于结束日期')
    await page.getByRole('button', { name: '2025年', exact: true }).click()
    await expect(page.getByRole('alert')).toHaveCount(0)
  })
  await test.step('monthly query shows actual API result and safe chart/table controls', async () => {
    await ask(page, '2025年销售额和订单数按月看')
    const result = page.locator('.query-result-anchor .result-card')
    await expect(result).toBeVisible()
    await expect(result.locator('canvas')).toBeVisible()
    await expect(result.getByRole('button', { name: '瀑布', exact: true })).toBeDisabled()
    await expect(result.locator('.waterfall-hint')).toContainText('单一指标')
    await result.getByRole('button', { name: '表格', exact: true }).click()
    await expect(result.locator('tbody tr')).toHaveCount(12)
    await expect(result.locator('thead')).toContainText('订单数')
    await result.getByRole('button', { name: '柱状', exact: true }).click()
    await expect(result.locator('canvas')).toBeVisible()
    await result.getByRole('button', { name: '口径与来源', exact: true }).click()
    const resultIds = await result.locator('.details-grid strong').allTextContents()
    protectedResultId = resultIds.find(value => /^[\da-f]{8}-[\da-f-]{27}$/.test(value)) || ''
    expect(protectedResultId).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath('02-query-result.png'), fullPage: true })
  })
  await test.step('CSV downloads a real authorized aggregate', async () => {
    const response = await context.request.get(`/api/results/${protectedResultId}/csv`)
    expect(response.status()).toBe(200)
    expect(response.headers()['content-type']).toContain('text/csv')
    const text = await response.text()
    expect(text).toContain('折扣后销售额')
    expect(text).toContain('2025-01')
    const event = page.waitForEvent('download')
    await page.locator('.query-result-anchor').getByRole('button', { name: '导出 CSV' }).click()
    const download = await event
    expect(await download.failure()).toBeNull()
    await download.saveAs(testInfo.outputPath('authorized-monthly.csv'))
  })
  await test.step('synchronous display-only follow-up keeps the same result, CSV and budget without refresh', async () => {
    const original = await (await context.request.get(`/api/results/${protectedResultId}`)).json()
    const budgetBefore = await page.locator('.assistant-footer').innerText()
    const submitted = page.waitForResponse(response => response.request().method() === 'POST' && /\/api\/conversations\/[^/]+\/runs$/.test(new URL(response.url()).pathname))
    await ask(page, '换成表格')
    const acknowledgement = await (await submitted).json()
    expect(acknowledgement.status).toBe('succeeded')
    expect(acknowledgement.result).toBeUndefined()
    const run = await (await context.request.get(`/api/runs/${acknowledgement.run_id}`)).json()
    expect(run.result_id).toBe(protectedResultId)
    expect(run.result).toEqual(original)
    expect(run.runtime).toMatchObject({ kind: 'presentation_reuse', model_calls: 0, aggregate_queries: 0 })
    const result = page.locator('.query-result-anchor .result-card')
    await expect(result.getByRole('button', { name: '表格', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(result.locator('tbody tr')).toHaveCount(12)
    await expect(result.locator('thead')).toContainText('订单数')
    await expect(page.locator('.assistant-footer')).toHaveText(budgetBefore)
    const csv = page.waitForResponse(response => new URL(response.url()).pathname === `/api/results/${protectedResultId}/csv`)
    const downloading = page.waitForEvent('download')
    await result.getByRole('button', { name: '导出 CSV' }).click()
    expect((await csv).status()).toBe(200)
    expect(await (await downloading).failure()).toBeNull()
  })
  await test.step('multi-turn scope change and refresh recover from server state', async () => {
    await ask(page, '按门店看')
    await page.locator('.query-result-anchor').getByRole('button', { name: '表格', exact: true }).click()
    await expect(page.locator('.query-result-anchor th').first()).toHaveText('门店')
    await page.reload()
    await expect(page.locator('.chat-message.user')).toHaveCount(3)
    await expect(page.locator('.query-result-anchor .result-card')).toBeVisible()
  })
  await test.step('comparison contribution produces reconciled waterfall, including negative deltas', async () => {
    await ask(page, '2025年9月比8月销售额变化来自哪些类别，用瀑布图')
    const result = page.locator('.query-result-anchor')
    await expect(result.getByRole('button', { name: '瀑布', exact: true })).toBeEnabled()
    await expect(result.getByRole('button', { name: '瀑布', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(result.locator('.waterfall-hint')).toHaveCount(0)
    await expect(result.locator('canvas')).toBeVisible()
    for (const name of ['表格', '柱状', '瀑布']) {
      await result.getByRole('button', { name, exact: true }).click()
      await expect(result.getByRole('button', { name, exact: true })).toHaveAttribute('aria-pressed', 'true')
    }
    await expect(result.locator('canvas')).toBeVisible()
    await expect(result.locator('.observations')).toContainText('贡献')
    await expect(result.getByRole('button', { name: '折线', exact: true })).toBeDisabled()
    await page.screenshot({ path: testInfo.outputPath('03-waterfall.png'), fullPage: true })
  })
  await test.step('unsupported and ambiguous questions terminate cleanly and preserve query control', async () => {
    await ask(page, '2025年退款金额是多少？')
    await expect(page.locator('.chat-message.assistant').last()).toContainText('不包含')
    await expect(page.locator('.working-message')).toHaveCount(0)
    await expect(page.locator('.query-result-anchor .result-card')).toHaveCount(0)
    await page.reload()
    await expect(page.locator('.chat-message.user')).toHaveCount(5)
    await expect(page.locator('.query-result-anchor .result-card')).toHaveCount(0)
    await ask(page, '今年销售额是多少？')
    await expect(page.locator('.chat-message.assistant').last()).toContainText('明确')
    await expect(page.locator('.working-message')).toHaveCount(0)
  })
  await test.step('reset cancel keeps history; confirm starts new server conversation', async () => {
    await page.getByRole('button', { name: '新建会话并重置上下文' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: '保留当前会话' }).click()
    await expect(page.locator('.chat-message.user')).toHaveCount(6)
    await page.getByRole('button', { name: '新建会话并重置上下文' }).click()
    await page.getByRole('button', { name: '新建会话', exact: true }).click()
    await expect(page.locator('.chat-message.user')).toHaveCount(0)
    await expect(page.locator('.assistant-welcome')).toBeVisible()
    await page.getByRole('button', { name: /分析记录/ }).first().click()
    await expect(page.locator('.history-row')).toHaveCount(1)
    await page.locator('.history-row').first().click()
    await expect(page.locator('.chat-message.user')).toHaveCount(6)
  })
  await test.step('second demo identity has smaller totals and cannot read first identity result', async () => {
    const loggedOut = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/auth/logout')
    await page.getByRole('button', { name: '退出登录' }).click()
    const response = await loggedOut
    expect(response.ok()).toBeTruthy()
    expect(await response.finished()).toBeNull()
    await expect(page.getByRole('heading', { name: '进入分析工作台', exact: true })).toBeVisible()
    await login(page, 'analyst')
    await expect(page.locator('.scope-chip')).toContainText('3 家门店')
    const me = await (await context.request.get('/api/me')).json()
    expect(me.allowed_store_ids).toHaveLength(3)
    const inaccessible = await context.request.get(`/api/results/${protectedResultId}`)
    expect(inaccessible.status()).toBe(404)
    const forbiddenCsv = await context.request.get(`/api/results/${protectedResultId}/csv`)
    expect(forbiddenCsv.status()).toBe(404)
    await ask(page, '2025年销售额按门店看')
    await page.locator('.query-result-anchor').getByRole('button', { name: '表格', exact: true }).click()
    const storeLabels = await page.locator('.query-result-anchor tbody tr td:first-child').allTextContents()
    expect(storeLabels.length).toBeGreaterThan(0)
    expect(storeLabels.length).toBeLessThanOrEqual(3)
    expect(storeLabels.every(label => me.allowed_store_ids.includes(Number(label.match(/#(\d+)$/)?.[1])))).toBeTruthy()
  })
  await test.step('mobile navigation and dashboard stay within viewport', async () => {
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(page.getByRole('button', { name: '打开菜单' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.getByRole('button', { name: '打开菜单' }).click()
    await page.getByRole('button', { name: '指标口径', exact: true }).click()
    await expect(page.getByRole('heading', { name: '统一口径，可信分析' })).toBeVisible()
    await expect(page.locator('.sidebar')).not.toHaveClass(/open/)
    await expect(page.locator('.sidebar')).not.toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath('04-mobile-definitions.png'), fullPage: true })
    await page.getByRole('button', { name: '打开菜单' }).click()
    await page.getByRole('button', { name: '销售概览', exact: true }).click()
    await expect(page.locator('.sidebar')).not.toBeInViewport()
    await page.screenshot({ path: testInfo.outputPath('05-mobile-dashboard.png'), fullPage: true })
  })
  expect(pageErrors).toEqual([])
})
