import { expect, test } from '@playwright/test'

test('real backend: bounded review, persisted report, annotation edit, export, trash and current-account access', async ({ page, context, request }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', error => pageErrors.push(error.message))
  await page.goto('/')
  await page.getByRole('textbox', { name: '账号', exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill('demo123')
  await page.getByRole('button', { name: '进入工作台', exact: true }).click()
  await expect(page.locator('.mode-badge')).toContainText('MOCK')
  await page.getByRole('button', { name: '销售复盘', exact: true }).click()
  await page.getByRole('button', { name: '2025 年 Q3 vs Q2', exact: true }).click()
  const runStarted = page.waitForResponse(response => response.request().method() === 'POST' && /\/api\/conversations\/[^/]+\/runs$/.test(new URL(response.url()).pathname))
  await page.getByRole('button', { name: '开始销售复盘', exact: true }).click()
  const run = await (await runStarted).json()
  await expect(page.locator('.review-result-heading')).toContainText('本次复盘已完成', { timeout: 30_000 })
  const finished = await (await context.request.get(`/api/runs/${run.run_id}`)).json()
  expect(finished.kind).toBe('review')
  expect(finished.review.query_count).toBeLessThanOrEqual(4)
  expect(finished.review.request.period).toMatchObject({ start: '2025-07-01', end: '2025-10-01' })
  expect(finished.review.evidence.length).toBe(finished.review.query_count)
  await expect(page.locator('.review-workspace .review-facts')).toContainText('数据事实')
  await expect(page.locator('.review-workspace .review-stop-note')).not.toContainText('query_limit_reached')
  await page.getByRole('button', { name: '保存报告', exact: true }).click()
  const title = `E2E 销售复盘 ${Date.now()}`
  await page.locator('.report-save-form').getByLabel('报告标题', { exact: true }).fill(title)
  await page.locator('.report-save-form').getByLabel('我的备注（可选）', { exact: true }).fill('核实后的业务备注')
  const createdResponse = page.waitForResponse(response => response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/reports')
  await page.getByRole('button', { name: '确认保存报告', exact: true }).click()
  const created = await (await createdResponse).json()
  const facts = created.facts
  await expect(page.locator('.reports-workspace .report-title-row')).toContainText(title)
  expect(page.url()).toContain(`#reports/${created.id}`)
  await page.reload()
  await expect(page.locator('.reports-workspace .report-title-row')).toContainText(title)
  await expect(page.locator('.report-annotations')).toContainText('核实后的业务备注')
  await page.getByRole('button', { name: '编辑批注', exact: true }).click()
  await page.locator('.report-editor').getByLabel('报告标题', { exact: true }).fill(`${title}（已核对）`)
  await page.locator('.report-editor').getByLabel('我的补充建议', { exact: true }).fill('<img src=x onerror=alert(1)> 核实后再行动')
  await page.getByRole('button', { name: '保存批注', exact: true }).click()
  await expect(page.locator('.report-alert')).toContainText('冻结数据事实未改变')
  expect(await page.locator('.report-annotations img').count()).toBe(0)
  const updated = await (await context.request.get(`/api/reports/${created.id}`)).json()
  expect(updated.facts).toEqual(facts)
  for (const [name, extension] of [['导出 Markdown', 'md'], ['导出 HTML', 'html']] as const) {
    const downloading = page.waitForEvent('download')
    await page.getByRole('button', { name, exact: true }).click()
    const download = await downloading
    expect(await download.failure()).toBeNull()
    await download.saveAs(testInfo.outputPath(`saved-report.${extension}`))
  }
  await page.getByRole('button', { name: '移入回收站', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '保留报告', exact: true }).click()
  await expect(page.getByRole('button', { name: '导出 HTML', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '移入回收站', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '移入回收站', exact: true }).click()
  await expect(page.getByRole('button', { name: '恢复报告', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '恢复报告', exact: true }).click()
  await expect(page.getByRole('button', { name: '导出 HTML', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '返回报告列表', exact: true }).click()
  await expect(page.locator('.report-list')).toContainText(`${title}（已核对）`)
  await page.goBack()
  await expect(page.locator('.report-title-row')).toContainText(`${title}（已核对）`)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('sales-report-mobile.png'), fullPage: true })
  // Independent second account: no report bytes or exports are available by guessing its id.
  await request.post('/api/auth/login', { data: { username: 'analyst', password: 'demo123' } })
  expect((await request.get(`/api/reports/${created.id}`)).status()).toBe(404)
  expect((await request.get(`/api/reports/${created.id}/export?format=html`)).status()).toBe(404)
  expect(pageErrors).toEqual([])
})
